sauce_connect: true
loopback: airtap.local
browsers:
  - name: chrome
    version: -1..latest
  - name: firefox
    version: -1..latest
  - name: safari
    version: 10..latest
  - name: microsoftedge
    version: -1..latest
  - name: iphone
    version:
      - 10.3
      - latest
