browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: microsoftedge
    version: latest
  - name: internet explorer
    version: latest
  - name: iphone
    version: latest
